### ISSUE TITLE
parameter

### ISSUE THREAD

**Issue by yuhua666** [ziplab/EcoFormer#2]
Hello, how is the on-chip energy consumption calculated? Why does the paper not give the traditional parameter quantity and calculation quantity to measure the degree of lightweight?

**Comment by liujingcs** [comment]
Our paper focuses on computation complexity bottleneck instead of #parameters of Transformers. As floating-point operations (FLOPs) cannot accurately reflect the computational cost in our proposed method, we measure the model complexity by the number of multiplications and additions, separately. 

To compute the on-chip energy, we first calculate FLOPs, where we count the multiply-accumulate operations for all layers. We also count the multiplications in the scaling operations. In this case, each multiply-accumulate operation consists of an addition and a multiplication. Then, the on-chip energy consumption can be calculated by: #multiplications * 3.7 (energy consumption for a 32-bit multiplication) + #additions * 0.9 (energy consumption for a 32-bit addition)
